### ISSUE TITLE
When I run "python bin/app.py"  (game

### ISSUE THREAD

**Issue by CentripetalQuake** [wzpan/Learn-Python-The-Hard-Way#6]
Traceback (most recent call last):
  File "bin/app.py", line 2, in <module>
    from bin import map
ImportError: No module named bin

**Comment by wzpan** [comment]
Did you run it in this way?

``` sh
export PYTHONPATH=$PYTHONPATH:.
python2 bin/app.py
```

**Comment by CentripetalQuake** [comment]
C:\WINDOWS\system32> $env:PYTHONPATH = "$env:PYTHONPATH;."
PS E:\workSpace\game\skeleton> python bin/app.py
Traceback (most recent call last):
  File "bin/app.py", line 2, in <module>
    from bin import map
ImportError: No module named bin
